# Generated by Django 4.0.6 on 2022-12-25 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseYear',
            fields=[
                ('CreatedBy', models.PositiveIntegerField(blank=True, null=True, verbose_name='Create by')),
                ('CreationTime', models.DateTimeField(auto_now_add=True, verbose_name='Time of Creation')),
                ('Year', models.IntegerField(primary_key=True, serialize=False, verbose_name='Year')),
                ('IsAbnormal', models.BooleanField(blank=True, default=False, null=True, verbose_name='Is the year abnormal')),
            ],
            options={
                'verbose_name': 'DatabaseYear',
                'verbose_name_plural': 'DatabaseYears',
                'db_table': 'DatabaseYear',
            },
        ),
        migrations.CreateModel(
            name='ImportDatabase',
            fields=[
                ('CreatedBy', models.PositiveIntegerField(blank=True, null=True, verbose_name='Create by')),
                ('CreationTime', models.DateTimeField(auto_now_add=True, verbose_name='Time of Creation')),
                ('DatabaseId', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('DatabaseName', models.CharField(blank=True, default='', max_length=225, null=True, verbose_name='Name of Database')),
                ('IsActive', models.BooleanField(blank=True, default=True, null=True, verbose_name='Is Active')),
            ],
            options={
                'verbose_name': 'Import Database',
                'verbose_name_plural': 'Import Databases',
                'db_table': 'ImportDatabase',
            },
        ),
        migrations.CreateModel(
            name='TradeInValueAdded',
            fields=[
                ('CreatedBy', models.PositiveIntegerField(blank=True, null=True, verbose_name='Create by')),
                ('CreationTime', models.DateTimeField(auto_now_add=True, verbose_name='Time of Creation')),
                ('TiVAId', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('InputCountry', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Input country')),
                ('InputSector', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Input Sector')),
                ('OutputCountry', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Output country')),
                ('OutputSector', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Output Sector')),
                ('ValueAdded', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Trade in Value Added')),
                ('DatabaseYear', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TiVAYears', to='Data.databaseyear')),
            ],
            options={
                'verbose_name': 'Trade in Value Added',
                'verbose_name_plural': 'Trade in Values Added',
                'db_table': 'TradeInValueAdded',
            },
        ),
        migrations.AddField(
            model_name='databaseyear',
            name='ImportDatabase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DatabaseYears', to='Data.importdatabase'),
        ),
    ]
