# Generated by Django 4.0.6 on 2022-12-24 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradeinvalueadded',
            name='Year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TiVAYears', to='Data.year'),
        ),
    ]
